### PR TITLE
Create a new form for registrations without needing a date of birth.

### PR DESCRIPTION
**Pull request by smarzban**
This would require a new Form class (perhaps BaseForm?)

It has 3 fields: username, password, next

The existing RegistrationForm can subclass the BaseForm and add the date of birth field for backwards compatibility.

### CODE REVIEW

**Comment by smarzban** [comment]
@smn @miltontony Is this right?

**Comment by smarzban** [comment]
@smn @miltontony I think like that I can update the date of birth anywhere else as well, am I right?

**Comment by smn** [comment]
I'm not entirely sure having a separate view (or URL) is a good idea. If people know about this (and they will, it's all open-source) then they'll be able to type in that URL manually and register without a date of birth even though it may be a requirement for the site.

I'm trying to think of ways of making this work differently.

**Comment by smarzban** [comment]
Resolved in PR #9

**Pull request closed without merging**
