### PR TITLE
show a warning message if country code was not added when mobile number is activated

### PR DESCRIPTION
**Pull request by smarzban**

### CODE REVIEW

**Comment by smarzban** [comment]
screen shot 2017-01-23 at 3 21 05 pm

**Comment by smarzban** [comment]
@miltontony @nathanbegbie @Ntu2koTrevor @codiebeulaine ready for review :)

**Comment by smarzban** [comment]
profile

**Comment by codiebeulaine** [comment]
@saeedmb8 👍

**Pull request merged**
